// List
export const INITIAL_STOCK = 'INITIAL_STOCK';
export const SAVE_STOCK = 'SAVE_STOCK';
export const REMOVE_STOCK = 'REMOVE_STOCK';
export const CHANGE_STOCK_ORDER = 'CHANGE_STOCK_ORDER';

// Loading
export const TABLE_LOADING = 'TABLE_LOADING';

// portfolio
export const INITIAL_PORTFOLIO = 'INITIAL_PORTFOLIO';
export const SAVE_PORTFOLIO = 'SAVE_PORTFOLIO';
export const REMOVE_PORTFOLIO = 'REMOVE_PORTFOLIO';
export const CHANGE_PORTFOLIO_ORDER = 'CHANGE_PORTFOLIO_ORDER';
export const CHANGE_STOCK_QUANTITY = 'CHANGE_STOCK_QUANTITY';
