// List
export const INITIAL_STOCK = "INITIAL_STOCK";
export const SAVE_STOCK = "SAVE_STOCK";
export const REMOVE_STOCK = "REMOVE_STOCK";
export const CHANGE_STOCK_ORDER = "CHANGE_STOCK_ORDER";

// Loading
export const TABLE_LOADING = "TABLE_LOADING";

// portfolio
export const INITIAL_PORTFOLIO_STOCK = "INITIAL_PORTFOLIO_STOCK";
export const SAVE_PORTFOLIO_STOCK = "SAVE_PORTFOLIO_STOCK";
export const REMOVE_PORTFOLIO_STOCK = "REMOVE_PORTFOLIO_STOCK";
export const CHANGE_PORTFOLIO_ORDER = "CHANGE_PORTFOLIO_ORDER";
